# Generated by Django 5.1.1 on 2024-09-21 14:57

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category_image', models.ImageField(null=True, upload_to=shop.models.get_file_name)),
                ('status', models.BooleanField(default=True, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('products_images', models.ImageField(blank=True, null=True, upload_to=shop.models.get_file_name)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('vendor', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
